<?php
require('header.php');

if(isset($_POST['update_password'])) {
    $current = $_POST['current_pass'];
    $new = $_POST['new_pass'];
    $new_confirm = $_POST['confirm_pass'];
    
    if($new !== $new_confirm) {
        $msg = alert('error', 'New passwords do not match!');
    } else {
        $admin_id = $_SESSION['adminId'] ?? 1;
        $q = "SELECT password FROM lab_admin_users WHERE id = $admin_id";
        $res = $con->query($q)->fetch_assoc();
        
        if(password_verify($current, $res['password'])) {
            $hashed = password_hash($new, PASSWORD_DEFAULT);
            $con->query("UPDATE lab_admin_users SET password = '$hashed' WHERE id = $admin_id");
            $msg = alert('success', 'Password updated successfully!');
        } else {
            $msg = alert('error', 'Current password is incorrect!');
        }
    }
}
?>

<div class="d-flex justify-content-between align-items-center mb-4 border-bottom pb-3">
    <h4 class="fw-bold mb-0 text-danger"><i class="bi bi-sliders me-2"></i>System Settings</h4>
</div>

<?= $msg ?? '' ?>

<div class="row g-4">
    <div class="col-md-6">
        <div class="card border-0 shadow-sm custom-card h-100">
            <div class="card-header bg-white p-3 border-bottom text-danger fw-bold">
                <i class="bi bi-person-lock me-2"></i>Change Admin Password
            </div>
            <div class="card-body p-4">
                <form method="POST">
                    <div class="mb-3">
                        <label class="form-label fw-medium text-secondary">Current Password</label>
                        <input type="password" name="current_pass" class="form-control bg-light" required>
                    </div>
                    <div class="mb-3">
                        <label class="form-label fw-medium text-secondary">New Password</label>
                        <input type="password" name="new_pass" class="form-control bg-light" required>
                    </div>
                    <div class="mb-4">
                        <label class="form-label fw-medium text-secondary">Confirm New Password</label>
                        <input type="password" name="confirm_pass" class="form-control bg-light" required>
                    </div>
                    <button type="submit" name="update_password" class="btn btn-danger w-100 shadow fw-bold"><i class="bi bi-check-circle me-1"></i> Update Password</button>
                </form>
            </div>
        </div>
    </div>
    
    <div class="col-md-6">
        <div class="card border-0 shadow-sm custom-card h-100">
            <div class="card-header bg-white p-3 border-bottom text-danger fw-bold">
                <i class="bi bi-info-circle me-2"></i>System Information
            </div>
            <div class="card-body p-4 lh-lg">
                <p class="mb-2"><strong class="me-2 text-secondary">System Name:</strong> BSU Laboratory Asset Management System (LAMS)</p>
                <p class="mb-2"><strong class="me-2 text-secondary">Version:</strong> 1.0.0</p>
                <p class="mb-2"><strong class="me-2 text-secondary">Developer:</strong> Generated by System</p>
                <p class="mb-0"><strong class="me-2 text-secondary">Contact Support:</strong> laboratory@bsu.edu.ph</p>
                <hr>
                <p class="text-muted small">
                    This system handles the inventory of Hot Kitchen, Cold Kitchen, Food & Beverages Service, and Laundry classes. It aims to reduce equipment loss through rigid tracking of item quantities during student reservations.
                </p>
            </div>
        </div>
    </div>
</div>

<?php require('footer.php'); ?>
